url: https://www.oxinabox.net
enforce_ssl: www.oxinabox.net

highlighter: rouge

markdown_ext: "markdown,mkdown,mkdn,mkd,md,txt"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

exclude:
  - "*.ipynb"


plugins:
  - jekyll-redirect-from
  - jekyll-feed
    
excerpt_separator: <!--more-->

