url: https://white.ucc.asn.au
enforce_ssl: white.ucc.asn.au

markdown_ext: "markdown,mkdown,mkdn,mkd,md,txt"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - "*.ipynb"


gems:
  - jekyll-redirect-from
  - jekyll-feed
    
excerpt_separator: <!--more-->

